sudo: true
language: python
python:
  - "3.6"
before_install:
  - sudo wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
  - sudo sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google-chrome.list'
  - sudo apt-get -y update
  - sudo apt-get install -y google-chrome-stable xvfb

  # install chromedriver
  - sudo apt-get install -yqq unzip
  - sudo wget -O /tmp/chromedriver.zip http://chromedriver.storage.googleapis.com/`curl -sS chromedriver.storage.googleapis.com/LATEST_RELEASE`/chromedriver_linux64.zip
  - sudo unzip /tmp/chromedriver.zip chromedriver -d /usr/local/bin/
  - pip install codecov flake8
install: "pip install ."
# command to - tests
script:
  - xvfb-run -a python setup.py test
  - codecov
  - flake8